palette = "dracula"

format = """
[┌─ ](background)\
$username\
$hostname\
$os $directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$fill $cmd_duration\
\
$c\
$nodejs\
$python\
$java\
$lua\
$swift\
$rust\
$golang\
$dart\
$kotlin\
$php\
$ruby\
$solidity\
\
$jobs\
$memory_usage\
$time\
$battery\
$line_break\
[└─](background)$character"""

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](orange)"

[fill]
symbol = '—'
style = 'background'

[os]
disabled = false

[os.symbols]
Alpine = " "
Android = " "
Arch = " "
Debian = " "
Garuda = "󰛓 "
Kali = " "
Linux = " "
Macos = " "
Raspbian = " "
Ubuntu = " "
Windows = "󰍲 "

[directory]
style = "purple"
read_only = " 󰌾"

[git_branch] # Shows active branch of the repo
symbol = " "
format = 'on [$symbol$branch(:$remote_branch)]($style) '
style = "cyan"

[git_state] # Shows operations in progress, such as: REBASING, BISECTING, etc
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "orange"

[git_metrics] # Show the number of added and deleted lines in the current repo
disabled = false

[docker_context]
symbol = " "
format = 'via [$symbol$context]($style) '

[cmd_duration]
min_time = 1000 # Shortest duration to show time for
format  = '[$duration]($style) '
style = "orange"
# show_notifications = true
# min_time_to_notify = 45_000

[jobs]
style = "red"
number_threshold = 1
format = "[$symbol$number]($style) "

[time]
disabled = false
style = "cyan"
format = "at [ $time]($style)"

# 'bold red' style and discharging_symbol when capacity is between 0% and 10%
[[battery.display]] 
threshold = 10
style = 'bold red'

# 'bold yellow' style and discharging_symbol when capacity is between 10% and 30%
[[battery.display]]
threshold = 30
style = 'bold yellow'

# Define Dracula color palette
[palettes.dracula]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"


[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "
format = 	'[$symbol($version )]($style)'

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "
format = 	'[$symbol($version )]($style)'

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
symbol = " "
format = 	'[$symbol($version )]($style)'

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "
format = 	'[$symbol($version )]($style)'

[julia]
symbol = " "

[kotlin]
symbol = " "
format = 	'[$symbol($version )]($style)'

[lua]
symbol = " "
format = 	'[$symbol($version )]($style)'

[memory_usage]
disabled = false
symbol = "󰍛"
threshold = 75
format = '$symbol [${ram}( | ${swap})]($style) '

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = "󰎙 "
format = 	'[$symbol($version )]($style)'

[ocaml]
symbol = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "
format = 	'[$symbol($version )]($style)'

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = " "
format = 	'[$symbol($version )]($style)'

[zig]
symbol = " "


